name: argentumage # you probably want to snapcraft register <name>
base: core18 # the base snap is the execution environment for this snap
version: '1.0.684' # just for humans, typically 1.2+git or 1.3.2
summary: An OpenSource Collectible Card Game # 79 char long summary
description: |
   Argentum Age is an open source digit collectible card game with tactical positioning, and a focus on limited    randomness to allow for maximum player skill. Argentum Age aims to provide all the excitement of a collectible card game without any gameplay altering In-App Purchases or other "pay to win" elements. A single player campaign mode as well as multiplayer are both available.

grade: stable # must be stable to release into candidate/stable channels
confinement: strict # use strict once you have the right plugs and slots
apps:
  argentumage:
     command: arg.launcher
     plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - audio-playback
      - pulseaudio
      - network
     slots:
      - mpris
     environment: #needed librarys for the game to start
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio"
      #needed to find swrast
      LIBGL_DRIVERS_PATH: "$LIBGL_DRIVERS_PATH:$SNAP/usr/lib/x86_64-linux-gnu/dri/"
parts:
##################### launcher Script, to avoid anura using a path with //
  launcher:
   source: ./launcher/
   plugin: dump
##################### citadel mod
  argentumage:
    plugin: nil
    source: https://github.com/davewx7/citadel.git
    source-type: git
    override-prime: |
     mkdir /root/prime/modules/citadel/
     mv /root/parts/argentumage/src/* /root/prime/modules/citadel/
  argentumicon:
   plugin: nil
   override-prime: | 
     cd /root/prime/modules/citadel
     convert aa-icon.ico argentum-age.png
     xdg-icon-resource install --novendor --size 64 argentum-age.png argentumage
#################### anura engine
  anura:
    plugin: make
    source: https://github.com/anura-engine/anura
    source-type: git
    artifacts: [INSTALL, MacOS, Makefile-safe, Makefile.ac100, Makefile.mingw, MinGW-build-instructions.txt, SConstruct, anura, compile-objects.cfg, eris_unit_tests.sh, images, lua_unit_tests.sh, modules, pull-v, restart-citadel.sh, steam_appid.txt, utils, LICENSE, Makefile, Makefile-win, Makefile.harmattan, Makefile.pandora, README.md, android, build, data, external, imgui, music, quickmake.sh, src, master-config.cfg, update, vs2013]
    build-packages:
    - graphicsmagick-imagemagick-compat
    - xdg-utils
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-iostreams1.65-dev
    - libboost-regex-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libsdl2-ttf-dev
    - libglew-dev
    - libpng-dev
    - libcairo-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libboost-locale1.65-dev
    stage-packages:
    - git
    - libasound2
    - libasyncns0
    - libboost-filesystem1.65.1
    - libboost-locale1.65.1
    - libboost-regex1.65.1
    - libboost-system1.65.1
    - libboost-thread1.65.1
    - libcairo2
    - libflac8
    - libfontconfig1
    - libfreetype6
    - libgl1
    - libglew2.0
    - libglvnd0
    - libglx0
    - libicu60
    - libjbig0
    - libjpeg-turbo8
    - libogg0
    - libpixman-1-0
    - libpng16-16
    - libpulse0
    - libsdl2-2.0-0
    - libsdl2-image-2.0-0
    - libsdl2-ttf-2.0-0
    - libsndfile1
    - libsndio6.1	
    - libtiff5
    - libvorbis0a
    - libvorbisenc2
    - libvorbisfile3
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libwebp6
    - libx11-6
    - libxau6
    - libxcb-render0
    - libxcb-shm0
    - libxcb1
    - libxcursor1
    - libxdmcp6
    - libxext6
    - libpulse-dev
    - mesa-utils
    - libgl1-mesa-glx

    
